name: Fetch Trends Data

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  fetch_trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          cd $GITHUB_WORKSPACE
          python fetch-trends.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-trends-data
          path: data/combined_trends_data.csv
